export const OriginalimgPATH = "https://image.tmdb.org/t/p/original/"
export const w500imgPATH = "https://image.tmdb.org/t/p/w500/"
export const YOUTUBE = "https://www.youtube.com/embed/"
export const baseUrl = ""
// export const baseUrl = "http://localhost:3001"